### PR TITLE
Create Esme.cs

### PR DESCRIPTION
**Pull request by meraleon**
I made this code bla blah

### CODE REVIEW

**Comment by tehreemharoon** [comment]
do better. pls fix!

**Comment by meraleon** [comment]
great job 
the class does not have explicit modifier please fix that now

**Comment by oakande1** [comment]
sjkndsejnksefjnkfemklejnkadwmklfn

**Comment by saulpz** [comment]
WAK TAKING YOU OUT THE COLLABORATIVE TEAM ASAP!!!!!!!!!

**Review by tehreemharoon — APPROVED** [review]

**Comment by saulpz** [comment]
YOUR FIRED

**Pull request merged**
